import { getTimeZoneAbbreviation, isDaylightSavingTime } from "./time-zone-abbreviations"

// 定义时区数据
export const timeZones = [
  // 亚洲
  { name: "北京", offset: 8, region: "亚洲" },
  { name: "上海", offset: 8, region: "亚洲" },
  { name: "香港", offset: 8, region: "亚洲" },
  { name: "台北", offset: 8, region: "亚洲" },
  { name: "东京", offset: 9, region: "亚洲" },
  { name: "大阪", offset: 9, region: "亚洲" },
  { name: "首尔", offset: 9, region: "亚洲" },
  { name: "新加坡", offset: 8, region: "亚洲" },
  { name: "吉隆坡", offset: 8, region: "亚洲" },
  { name: "曼谷", offset: 7, region: "亚洲" },
  { name: "雅加达", offset: 7, region: "亚洲" },
  { name: "河内", offset: 7, region: "亚洲" },
  { name: "马尼拉", offset: 8, region: "亚洲" },
  { name: "新德里", offset: 5.5, region: "亚洲" },
  { name: "孟买", offset: 5.5, region: "亚洲" },
  { name: "加尔各答", offset: 5.5, region: "亚洲" },
  { name: "卡拉奇", offset: 5, region: "亚洲" },
  { name: "迪拜", offset: 4, region: "亚洲" },
  { name: "阿布扎比", offset: 4, region: "亚洲" },
  { name: "伊斯坦布尔", offset: 3, region: "亚洲" },
  { name: "耶路撒冷", offset: 2, region: "亚洲" },
  { name: "利雅得", offset: 3, region: "亚洲" },
  { name: "德黑兰", offset: 3.5, region: "亚洲" },
  { name: "巴格达", offset: 3, region: "亚洲" },
  { name: "乌兰巴托", offset: 8, region: "亚洲" },
  { name: "喀布尔", offset: 4.5, region: "亚洲" },
  { name: "达卡", offset: 6, region: "亚洲" },
  { name: "科伦坡", offset: 5.5, region: "亚洲" },
  { name: "仰光", offset: 6.5, region: "亚洲" },
  { name: "金边", offset: 7, region: "亚洲" },
  { name: "万象", offset: 7, region: "亚洲" },
  { name: "阿斯塔纳", offset: 6, region: "亚洲" },
  { name: "塔什干", offset: 5, region: "亚洲" },

  // 欧洲
  { name: "伦敦", offset: 0, region: "欧洲" },
  { name: "都柏林", offset: 0, region: "欧洲" },
  { name: "里斯本", offset: 0, region: "欧洲" },
  { name: "巴黎", offset: 1, region: "欧洲" },
  { name: "马德里", offset: 1, region: "欧洲" },
  { name: "罗马", offset: 1, region: "欧洲" },
  { name: "柏林", offset: 1, region: "欧洲" },
  { name: "阿姆斯特丹", offset: 1, region: "欧洲" },
  { name: "布鲁塞尔", offset: 1, region: "欧洲" },
  { name: "苏黎世", offset: 1, region: "欧洲" },
  { name: "日内瓦", offset: 1, region: "欧洲" },
  { name: "维也纳", offset: 1, region: "欧洲" },
  { name: "斯德哥尔摩", offset: 1, region: "欧洲" },
  { name: "哥本哈根", offset: 1, region: "欧洲" },
  { name: "奥斯陆", offset: 1, region: "欧洲" },
  { name: "赫尔辛基", offset: 2, region: "欧洲" },
  { name: "华沙", offset: 1, region: "欧洲" },
  { name: "布达佩斯", offset: 1, region: "欧洲" },
  { name: "布拉格", offset: 1, region: "欧洲" },
  { name: "雅典", offset: 2, region: "欧洲" },
  { name: "莫斯科", offset: 3, region: "欧洲" },
  { name: "圣彼得堡", offset: 3, region: "欧洲" },
  { name: "基辅", offset: 2, region: "欧洲" },
  { name: "明斯克", offset: 3, region: "欧洲" },
  { name: "布加勒斯特", offset: 2, region: "欧洲" },
  { name: "索非亚", offset: 2, region: "欧洲" },
  { name: "贝尔格莱德", offset: 1, region: "欧洲" },
  { name: "萨拉热窝", offset: 1, region: "欧洲" },
  { name: "塔林", offset: 2, region: "欧洲" },
  { name: "里加", offset: 2, region: "欧洲" },
  { name: "维尔纽斯", offset: 2, region: "欧洲" },

  // 北美洲
  { name: "纽约", offset: -5, region: "北美洲" },
  { name: "华盛顿", offset: -5, region: "北美洲" },
  { name: "波士顿", offset: -5, region: "北美洲" },
  { name: "芝加哥", offset: -6, region: "北美洲" },
  { name: "多伦多", offset: -5, region: "北美洲" },
  { name: "蒙特利尔", offset: -5, region: "北美洲" },
  { name: "温哥华", offset: -8, region: "北美洲" },
  { name: "洛杉矶", offset: -8, region: "北美洲" },
  { name: "旧金山", offset: -8, region: "北美洲" },
  { name: "西雅图", offset: -8, region: "北美洲" },
  { name: "拉斯维加斯", offset: -8, region: "北美洲" },
  { name: "丹佛", offset: -7, region: "北美洲" },
  { name: "凤凰城", offset: -7, region: "北美洲" },
  { name: "达拉斯", offset: -6, region: "北美洲" },
  { name: "休斯顿", offset: -6, region: "北美洲" },
  { name: "迈阿密", offset: -5, region: "北美洲" },
  { name: "亚特兰大", offset: -5, region: "北美洲" },
  { name: "费城", offset: -5, region: "北美洲" },
  { name: "底特律", offset: -5, region: "北美洲" },
  { name: "墨西哥城", offset: -6, region: "北美洲" },
  { name: "哈瓦那", offset: -5, region: "北美洲" },
  { name: "渥太华", offset: -5, region: "北美洲" },
  { name: "卡尔加里", offset: -7, region: "北美洲" },
  { name: "埃德蒙顿", offset: -7, region: "北美洲" },
  { name: "温尼伯", offset: -6, region: "北美洲" },
  { name: "魁北克", offset: -5, region: "北美洲" },
  { name: "安克雷奇", offset: -9, region: "北美洲" },
  { name: "檀香山", offset: -10, region: "北美洲" },

  // 南美洲
  { name: "里约热内卢", offset: -3, region: "南美洲" },
  { name: "圣保罗", offset: -3, region: "南美洲" },
  { name: "布宜诺斯艾利斯", offset: -3, region: "南美洲" },
  { name: "蒙得维的亚", offset: -3, region: "南美洲" },
  { name: "圣地亚哥", offset: -4, region: "南美洲" },
  { name: "利马", offset: -5, region: "南美洲" },
  { name: "波哥大", offset: -5, region: "南美洲" },
  { name: "卡拉卡斯", offset: -4, region: "南美洲" },
  { name: "基多", offset: -5, region: "南美洲" },
  { name: "拉巴斯", offset: -4, region: "南美洲" },
  { name: "亚松森", offset: -4, region: "南美洲" },
  { name: "巴西利亚", offset: -3, region: "南美洲" },
  { name: "麦德林", offset: -5, region: "南美洲" },
  { name: "瓜亚基尔", offset: -5, region: "南美洲" },
  { name: "马瑙斯", offset: -4, region: "南美洲" },

  // 大洋洲
  { name: "悉尼", offset: 10, region: "大洋洲" },
  { name: "墨尔本", offset: 10, region: "大洋洲" },
  { name: "堪培拉", offset: 10, region: "大洋洲" },
  { name: "布里斯班", offset: 10, region: "大洋洲" },
  { name: "珀斯", offset: 8, region: "大洋洲" },
  { name: "阿德莱德", offset: 9.5, region: "大洋洲" },
  { name: "达尔文", offset: 9.5, region: "大洋洲" },
  { name: "霍巴特", offset: 10, region: "大洋洲" },
  { name: "奥克兰", offset: 12, region: "大洋洲" },
  { name: "惠灵顿", offset: 12, region: "大洋洲" },
  { name: "基督城", offset: 12, region: "大洋洲" },
  { name: "苏瓦", offset: 12, region: "大洋洲" },
  { name: "努美阿", offset: 11, region: "大洋洲" },
  { name: "阿皮亚", offset: 13, region: "大洋洲" },
  { name: "霍尼亚拉", offset: 11, region: "大洋洲" },
  { name: "塔拉瓦", offset: 12, region: "大洋洲" },
  { name: "帕皮提", offset: -10, region: "大洋洲" },

  // 非洲
  { name: "开罗", offset: 2, region: "非洲" },
  { name: "约翰内斯堡", offset: 2, region: "非洲" },
  { name: "开普敦", offset: 2, region: "非洲" },
  { name: "拉各斯", offset: 1, region: "非洲" },
  { name: "内罗毕", offset: 3, region: "非洲" },
  { name: "亚的斯亚贝巴", offset: 3, region: "非洲" },
  { name: "卡萨布兰卡", offset: 0, region: "非洲" },
  { name: "阿尔及尔", offset: 1, region: "非洲" },
  { name: "突尼斯", offset: 1, region: "非洲" },
  { name: "的黎波里", offset: 2, region: "非洲" },
  { name: "喀土穆", offset: 2, region: "非洲" },
  { name: "阿克拉", offset: 0, region: "非洲" },
  { name: "达喀尔", offset: 0, region: "非洲" },
  { name: "亚穆苏克罗", offset: 0, region: "非洲" },
  { name: "阿比让", offset: 0, region: "非洲" },
  { name: "金沙萨", offset: 1, region: "非洲" },
  { name: "卢萨卡", offset: 2, region: "非洲" },
  { name: "哈拉雷", offset: 2, region: "非洲" },
  { name: "马普托", offset: 2, region: "非洲" },
  { name: "达累斯萨拉姆", offset: 3, region: "非洲" },
  { name: "坎帕拉", offset: 3, region: "非洲" },
  { name: "基加利", offset: 2, region: "非洲" },
  { name: "布拉柴维尔", offset: 1, region: "非洲" },
  { name: "罗安达", offset: 1, region: "非洲" },
  { name: "温得和克", offset: 2, region: "非洲" },
  { name: "杜阿拉", offset: 1, region: "非洲" },

  // 南极洲
  { name: "南极洲麦克默多站", offset: 12, region: "南极洲" },
  { name: "南极洲阿蒙森-斯科特站", offset: 12, region: "南极洲" },
  { name: "南极洲沃斯托克站", offset: 6, region: "南极洲" },
  { name: "南极洲长城站", offset: -3, region: "南极洲" },
  { name: "南极洲中山站", offset: 7, region: "南极洲" },
]

/**
 * 获取时区信息，包括缩写
 * @param offset 时区偏移量
 * @param date 日期，用于判断是否是夏令时
 * @returns 时区信息
 */
export function getTimeZoneInfo(offset: number, date: Date = new Date()) {
  const isDST = isDaylightSavingTime(date, offset)
  const tzAbbr = getTimeZoneAbbreviation(offset, isDST)

  return {
    offset,
    isDST,
    abbreviation: tzAbbr.abbr,
    name: tzAbbr.name,
  }
}
